AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - vendor/**/*
    - bin/**/*

require:
  - rubocop-performance

Style/Documentation:
  Enabled: false  

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
